version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=marketplace_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db  
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379  
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
